/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type {
  BaseContract,
  BigNumberish,
  BytesLike,
  FunctionFragment,
  Result,
  Interface,
  EventFragment,
  AddressLike,
  ContractRunner,
  ContractMethod,
  Listener,
} from "ethers";
import type {
  TypedContractEvent,
  TypedDeferredTopicFilter,
  TypedEventLog,
  TypedLogDescription,
  TypedListener,
  TypedContractMethod,
} from "./common";

export declare namespace CarbonCertificate {
  export type CertificateStruct = {
    certId: string;
    companyCIN: string;
    landId: string;
    credits: BigNumberish;
    validFrom: BigNumberish;
    validTo: BigNumberish;
    issuedBy: AddressLike;
    issuedAt: BigNumberish;
  };

  export type CertificateStructOutput = [
    certId: string,
    companyCIN: string,
    landId: string,
    credits: bigint,
    validFrom: bigint,
    validTo: bigint,
    issuedBy: string,
    issuedAt: bigint
  ] & {
    certId: string;
    companyCIN: string;
    landId: string;
    credits: bigint;
    validFrom: bigint;
    validTo: bigint;
    issuedBy: string;
    issuedAt: bigint;
  };
}

export interface CarbonCertificateInterface extends Interface {
  getFunction(
    nameOrSignature:
      | "certificateExists"
      | "certificates"
      | "getCertificate"
      | "governmentAdmin"
      | "issueCertificate"
      | "verifyCertificate"
  ): FunctionFragment;

  getEvent(nameOrSignatureOrTopic: "CertificateIssued"): EventFragment;

  encodeFunctionData(
    functionFragment: "certificateExists",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "certificates",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "getCertificate",
    values: [string]
  ): string;
  encodeFunctionData(
    functionFragment: "governmentAdmin",
    values?: undefined
  ): string;
  encodeFunctionData(
    functionFragment: "issueCertificate",
    values: [string, string, string, BigNumberish, BigNumberish, BigNumberish]
  ): string;
  encodeFunctionData(
    functionFragment: "verifyCertificate",
    values: [string]
  ): string;

  decodeFunctionResult(
    functionFragment: "certificateExists",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "certificates",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "getCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "governmentAdmin",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "issueCertificate",
    data: BytesLike
  ): Result;
  decodeFunctionResult(
    functionFragment: "verifyCertificate",
    data: BytesLike
  ): Result;
}

export namespace CertificateIssuedEvent {
  export type InputTuple = [
    certId: string,
    companyCIN: string,
    credits: BigNumberish,
    issuedAt: BigNumberish
  ];
  export type OutputTuple = [
    certId: string,
    companyCIN: string,
    credits: bigint,
    issuedAt: bigint
  ];
  export interface OutputObject {
    certId: string;
    companyCIN: string;
    credits: bigint;
    issuedAt: bigint;
  }
  export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>;
  export type Filter = TypedDeferredTopicFilter<Event>;
  export type Log = TypedEventLog<Event>;
  export type LogDescription = TypedLogDescription<Event>;
}

export interface CarbonCertificate extends BaseContract {
  connect(runner?: ContractRunner | null): CarbonCertificate;
  waitForDeployment(): Promise<this>;

  interface: CarbonCertificateInterface;

  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  on<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  once<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    listener: TypedListener<TCEvent>
  ): Promise<this>;
  once<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    listener: TypedListener<TCEvent>
  ): Promise<this>;

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>;
  removeAllListeners<TCEvent extends TypedContractEvent>(
    event?: TCEvent
  ): Promise<this>;

  certificateExists: TypedContractMethod<[arg0: string], [boolean], "view">;

  certificates: TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, string, bigint] & {
        certId: string;
        companyCIN: string;
        landId: string;
        credits: bigint;
        validFrom: bigint;
        validTo: bigint;
        issuedBy: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;

  getCertificate: TypedContractMethod<
    [_certId: string],
    [CarbonCertificate.CertificateStructOutput],
    "view"
  >;

  governmentAdmin: TypedContractMethod<[], [string], "view">;

  issueCertificate: TypedContractMethod<
    [
      _certId: string,
      _companyCIN: string,
      _landId: string,
      _credits: BigNumberish,
      _validFrom: BigNumberish,
      _validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;

  verifyCertificate: TypedContractMethod<[_certId: string], [boolean], "view">;

  getFunction<T extends ContractMethod = ContractMethod>(
    key: string | FunctionFragment
  ): T;

  getFunction(
    nameOrSignature: "certificateExists"
  ): TypedContractMethod<[arg0: string], [boolean], "view">;
  getFunction(
    nameOrSignature: "certificates"
  ): TypedContractMethod<
    [arg0: string],
    [
      [string, string, string, bigint, bigint, bigint, string, bigint] & {
        certId: string;
        companyCIN: string;
        landId: string;
        credits: bigint;
        validFrom: bigint;
        validTo: bigint;
        issuedBy: string;
        issuedAt: bigint;
      }
    ],
    "view"
  >;
  getFunction(
    nameOrSignature: "getCertificate"
  ): TypedContractMethod<
    [_certId: string],
    [CarbonCertificate.CertificateStructOutput],
    "view"
  >;
  getFunction(
    nameOrSignature: "governmentAdmin"
  ): TypedContractMethod<[], [string], "view">;
  getFunction(
    nameOrSignature: "issueCertificate"
  ): TypedContractMethod<
    [
      _certId: string,
      _companyCIN: string,
      _landId: string,
      _credits: BigNumberish,
      _validFrom: BigNumberish,
      _validTo: BigNumberish
    ],
    [void],
    "nonpayable"
  >;
  getFunction(
    nameOrSignature: "verifyCertificate"
  ): TypedContractMethod<[_certId: string], [boolean], "view">;

  getEvent(
    key: "CertificateIssued"
  ): TypedContractEvent<
    CertificateIssuedEvent.InputTuple,
    CertificateIssuedEvent.OutputTuple,
    CertificateIssuedEvent.OutputObject
  >;

  filters: {
    "CertificateIssued(string,string,uint256,uint256)": TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
    CertificateIssued: TypedContractEvent<
      CertificateIssuedEvent.InputTuple,
      CertificateIssuedEvent.OutputTuple,
      CertificateIssuedEvent.OutputObject
    >;
  };
}
